apiVersion: apps/v1
kind: Deployment
metadata:
  name: alkalmazas2
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alkalmazas2
  template:
    metadata:
      labels:
        app: alkalmazas2
    spec:
      containers:
      - name: alkalmazas2
        image: calliotel/nwm_allinone
        imagePullPolicy: Always
        env:
            - name: SSH_KEY
              value: <hidden>
            - name: GIT_REPO
              value: https://github.com/calliotel/Provisioner.git
        resources:
          limits:
            memory: "128Mi"
            cpu: "500m"
        ports:
        - containerPort: 80
---
