apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: alkalmazas2
  namespace: default
spec:
  ingressClassName: nginx
  rules:
  - host: localhost
    http:
      paths:
      - backend:
          service:
            name: alkalmazas2
            port:
              number: 80
        path: /
        pathType: Prefix
