apiVersion: v1
kind: ReplicationController
metadata:
  name: alkalmazas2
spec:
  replicas: 1
  selector:
    app: alkalmazas2
  template:
    metadata:
      name: alkalmazas2
      labels:
        app: alkalmazas2
    spec:
      containers:
        - name: alkalmazas2
          image: calliotel/nwm_allinone
          ports:
            - containerPort: 80
